title: K8sReady
description: Platform Engineering, Kubernetes and Open Source Infrastructure Tooling
baseurl: ""
url: "https://www.k8sready.com"
repository: pierinho13/pierinho13.github.io

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Permalinks
permalink: pretty

# Blog defaults
defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"
